__title__ = 'tweet-generator'
__description__ = 'Python Randomized Tweet Generator'
__url__ = 'http://www.github.com/oliviersm199'
__version__ = '0.0.3'
__build__ = None
__author__ = 'Olivier Simard-Morissette'
__author_email__ = 'olivier.morissette@gmail.com'
__license__ = 'GNU General Public License v3.0'
__copyright__ = 'Copyright 2018 Olivier Simard-Morissette'